### ISSUE TITLE
ShowUser vs User

### ISSUE THREAD

**Issue by ralf-t** [Iionsroar/fastapi_tut#6]
ShowUser returns a json without the password itself compared sa User

**Comment by Iionsroar** [comment]
User returns json w/ hashed_password, same sa ShowUser. UserCreate at UserUpdate lang may raw password attributes.

Though according sa comment at [Can I Expose The Hashed Salt + Password?](https://stackoverflow.com/questions/15777143/can-i-expose-the-hashed-salt-password), insecure pa ring iexpose yung hashed_password.

Dun sa case ng api naten, yung admin lang may access sa read_user. Current user lang rin nakakapagquery sa sariling info aside from admin. Idk sa client-side vulnerabilities so suggest ko na lang na imodify yung ShowUser into:

```python
class ShowUser(UserInDBBase):
	pass
```

where

```python
class UserBase(SQLModel):
	username : str
	email: Optional[EmailStr]
	full_name: Optional[str] = Field(index=True)
	is_superuser: bool = False
	last_name : str
	first_name : str
	is_teacher : bool = False
	is_student : bool = False

class PKModel(SQLModel):
	id: Optional[int] = Field(default=None, primary_key=True)

class UserInDBBase(UserBase, PKModel):
	class Config:
		orm_mode = True
```

**Comment by ralf-t** [comment]
aight
